# Generated by Django 5.1.6 on 2025-02-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_background_color_profile_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_image',
        ),
    ]
